// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC45lfr21tPJE8wt4CkJA7ey1w-bHl5P8E',
    appId: '1:523952275460:web:bf4864f8c1b756020bb551',
    messagingSenderId: '523952275460',
    projectId: 'fretefind',
    authDomain: 'fretefind.firebaseapp.com',
    databaseURL: 'https://fretefind-default-rtdb.firebaseio.com',
    storageBucket: 'fretefind.appspot.com',
    measurementId: 'G-YCN4XSSKWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2eTL7KhdWPs9EQzggl6q8tSCXedcfhns',
    appId: '1:523952275460:android:73e3bc627dc517d80bb551',
    messagingSenderId: '523952275460',
    projectId: 'fretefind',
    databaseURL: 'https://fretefind-default-rtdb.firebaseio.com',
    storageBucket: 'fretefind.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6jbfdXJK85yns3V4j4-Nj2MYR91y0PCk',
    appId: '1:523952275460:ios:261c6528a43e809e0bb551',
    messagingSenderId: '523952275460',
    projectId: 'fretefind',
    databaseURL: 'https://fretefind-default-rtdb.firebaseio.com',
    storageBucket: 'fretefind.appspot.com',
    iosBundleId: 'com.example.fretefindDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6jbfdXJK85yns3V4j4-Nj2MYR91y0PCk',
    appId: '1:523952275460:ios:25e46c6237a093f40bb551',
    messagingSenderId: '523952275460',
    projectId: 'fretefind',
    databaseURL: 'https://fretefind-default-rtdb.firebaseio.com',
    storageBucket: 'fretefind.appspot.com',
    iosBundleId: 'com.example.fretefind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC45lfr21tPJE8wt4CkJA7ey1w-bHl5P8E',
    appId: '1:523952275460:web:d6748a169ce1d4d30bb551',
    messagingSenderId: '523952275460',
    projectId: 'fretefind',
    authDomain: 'fretefind.firebaseapp.com',
    databaseURL: 'https://fretefind-default-rtdb.firebaseio.com',
    storageBucket: 'fretefind.appspot.com',
    measurementId: 'G-306XGLQC1Y',
  );
}